name: Create branch for issue

on:
  project_card:
    types: [moved]

jobs:
  create-branch:
    name: Create branch
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Get project column name
        id: project_column
        uses: korti11/moved-to-column@v0.1
      - name: Get issue
        if: steps.project_column.outputs.column_name == 'In progress'
        id: issue
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: octokit/request-action@v1.x
        with:
          route: GET ${{github.event.project_card.content_url}}
          Authorization: token ${{secrets.GITHUB_TOKEN}}
          mediaType: '{"previews": ["symmetra"]}'
      - name: Parse to JSON
        if: steps.project_column.outputs.column_name == 'In progress'
        id: issue_json
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{steps.issue.outputs.data}}
          number: "number"
      - name: Generate branch name
        if: steps.project_column.outputs.column_name == 'In progress'
        id: branch_name
        uses: korti11/issue-to-branch-name@v0.1
        with:
          issue: ${{steps.issue_json.outputs.number}}
          prefix: 'feature/'
      - name: Create branch
        if: steps.project_column.outputs.column_name == 'In progress'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: ${{steps.branch_name.outputs.branch_name}}