name: Create branch for issue

on:
  project_card:
    types: [moved]

jobs:
  create-branch:
    name: Create branch
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Get project column name
        id: project_column
        uses: korti11/moved-to-column@v0.1
      - name: Get issue
        if: steps.project_column.outputs.column_name == 'In progress'
        id: issue
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: octokit/request-action@v1.x
        with:
          route: GET ${{github.event.project_card.content_url}}
          Authorization: token ${{secrets.GITHUB_TOKEN}}
          mediaType: '{"previews": ["symmetra"]}'
      - name: Parse to JSON
        if: steps.project_column.outputs.column_name == 'In progress'
        id: issue_json
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{steps.issue.outputs.data}}
          number: "number"
          title: "title"
      - name: Formate title
        if: steps.project_column.outputs.column_name == 'In progress'
        id: formated_title
        uses: frabert/replace-string-action@v1.1
        with:
          pattern: '[ ]+'
          flags: 'g'
          string: ${{steps.issue_json.outputs.title}}
          replace-with: '-'
      - run: echo ${{steps.formated_title.outputs.replaced}}
      - name: Create branch
        if: steps.project_column.outputs.column_name == 'In progress'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: ${{format('feature/{0}-{1}', steps.issue_json.outputs.number, steps.formated_title.outputs.replaced)}}