name: Create feature pull request

on:
  project_card:
    types: [moved]

jobs:
  pull-request-on-feature-branch:
    name: Pull request from feature branch in to master branch
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Get project column name
        id: project_column
        uses: korti11/moved-to-column@v0.1
      - name: Get issue
        if: steps.project_column.outputs.column_name == 'In progress'
        id: issue
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: octokit/request-action@v1.x
        with:
          route: GET ${{github.event.project_card.content_url}}
          Authorization: token ${{secrets.GITHUB_TOKEN}}
          mediaType: '{"previews": ["symmetra"]}'
      - name: Parse issue to JSON
        if: steps.project_column.outputs.column_name == 'In progress'
        id: issue_json
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{steps.issue.outputs.data}}
          number: "number"
      - name: Find branch
        if: steps.project_column.outputs.column_name == 'In progress'
        id: find_branch
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: octokit/request-action@v1.x
        with:
          route: GET ${{format('https://api.github.com/repos/{0}/{1}/git/matching-refs/heads/feature/{2}', 'korti11', 'android-actions-playground', steps.issue_json.outputs.number)}}
          Authorization: token ${{secrets.GITHUB_TOKEN}}
      - name: Parse branch name to JSON
        if: steps.project_column.outputs.column_name == 'In progress'
        id: branch_json
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{steps.find_branch.outputs.data}}
          branch_name: "[0].ref"
      - name: Check out branch
        if: steps.project_column.outputs.column_name == 'In progress'
        uses: actions/checkout@v1
        with:
          ref: ${{steps.branch_json.outputs.branch_name}}
      - name: Create pull request
        if: steps.project_column.outputs.column_name == 'In progress'
        uses: repo-sync/pull-request@v2.0.1
        with:
          source_branch: ${{steps.branch_json.outputs.branch_name}}
          default_branch: 'master'
          pr_title: "Pulling ${{steps.branch_json.outputs.branch_name}} into master"
          pr_body: ":crown: *An automated PR*"
          pr_reviewer: "korti11"
          pr_assignee: "korti11"
          pr_label: "auto-pr"
          github_token: ${{secrets.GITHUB_TOKEN}}